CREATE TABLE clientes (
	cpf CHAR(14) PRIMARY KEY UNIQUE,
	nome VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	telefone CHAR(13) NOT NULL UNIQUE,
	cep CHAR(9)
);

CREATE TABLE categorias (
	id SERIAL PRIMARY KEY,
	categoria VARCHAR(20)
);